/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QoreClientHandle {
  sendOnStream(streamId: number, data: Uint8Array, fin: boolean): Promise<void>
}

export declare class QoreServerHandle {
  sendData(peer: string, streamId: number, data: Uint8Array): Promise<void>
}

export declare function connectToServer(host: string, port: number, callback: (event: QoreEvent) => void): Promise<QoreClientHandle>

export interface QoreEvent {
  eventType: string
  peer: string
  streamId?: number
  data?: Uint8Array
}

export declare function startServer(port: number, certPath: string, keyPath: string, callback: (event: QoreEvent) => void): Promise<QoreServerHandle>
