/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QoreServerHandle {
  sendData(peer: string, streamId: number, data: Uint8Array): Promise<void>
}

export interface QoreEvent {
  eventType: string
  peer: string
  streamId?: number
  data?: Uint8Array
}

export declare function startServer(port: number, certPath: string, keyPath: string, callback: (event: QoreEvent) => void): Promise<QoreServerHandle>
