name: Automate CD to NPM

env:
  DEBUG: napi:*
  APP_NAME: qore-quic
  MACOSX_DEPLOYMENT_TARGET: '10.13'

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.bump.outputs.ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci

      - name: Config Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Bump
        id: bump
        run: |
          npm version patch --force -m "chore(release): %s"
          NEW_VER=v$(node -p "require('./package.json').version")
          git push origin main
          git push origin $NEW_VER
          echo "ver=$NEW_VER" >> $GITHUB_OUTPUT

  build:
    needs: bump-version
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            build: npm run build --platform --release
            target: x86_64-pc-windows-msvc
          - host: macos-latest
            build: npm run build --platform --release
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            build: npm run build --platform --release
            target: x86_64-unknown-linux-gnu

    name: Build - ${{ matrix.settings.host }} - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.new_version }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Build
        run: ${{ matrix.settings.build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: "*.node"
          if-no-files-found: error

  publish:
    name: Publish
    needs: [bump-version, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.new_version }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifacts
        run: |
          mv artifacts/bindings-*/*.node .

      - name: Publish to NPM
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
